# Generated by Django 3.0.4 on 2020-04-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='list_services',
            field=models.TextField(default=''),
        ),
    ]
