# Generated by Django 3.0.4 on 2020-04-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicpatients',
            old_name='name',
            new_name='nickname',
        ),
        migrations.AddField(
            model_name='clinicpatients',
            name='owner',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='clinicpatients',
            name='patient_type',
            field=models.CharField(default='', max_length=150),
        ),
    ]
